services:
  - type: web
    name: streamlit-app
    env: python
    buildCommand: "./setup.sh && pip install -r requirements.txt"
    startCommand: "streamlit run main.py"
    repo: https://github.com/SanyamGarg02/AI-Medical-Scribe
    branch: main
