services:
  - type: web
    name: streamlit-app
    env: python
    buildCommand: "./setup.sh && pip install -r requirements.txt"
    startCommand: "streamlit run main.py"
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME
    branch: main
